Repository GearsAD/CloudGraphs.jl, pull requests merged in 2018-10, with the labels that each got.

#37 Maintenance/julia07
  .travis.yml
  REQUIRE
  src/BigData.jl
  src/CloudGraphs.jl
  src/CommonStructs.jl
  test/BigData.jl
  test/CloudGraphSetup.jl
  test/CloudGraphs.jl
  test/runtests.jl
Labels: v0.7/1.0

#38 Maintenance/switchmongoc
  .travis.yml
  REQUIRE
  src/BigData.jl
  src/CloudGraphs.jl
  src/CommonStructs.jl
  test/BigData.jl
  test/CloudGraphSetup.jl
  test/CloudGraphs.jl
  test/REQUIRE
  test/runPerformanceTests.jl
  test/runtests.jl
Labels: dependencies, v0.7/1.0

#39 new Mongoc version, dev not required
  .travis.yml
  REQUIRE
Labels: Travis, dependencies, v0.7/1.0
